# Generated by Django 4.1.7 on 2023-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=32)),
                ('Type', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('Engine', models.CharField(max_length=256)),
                ('Gears', models.CharField(max_length=256)),
                ('vimg', models.CharField(max_length=500)),
            ],
        ),
    ]
