# Generated by Django 4.1.7 on 2023-03-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Honda',
        ),
    ]
