# Generated by Django 4.1.7 on 2023-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_rename_hero_honda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bajaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=32)),
                ('Type', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('Engine', models.CharField(max_length=256)),
                ('Gears', models.CharField(max_length=256)),
                ('vimg', models.CharField(max_length=500)),
            ],
        ),
    ]
