# Generated by Django 4.1.7 on 2023-04-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
